server:           irc.elisa.fi
port:             6667
nick:             my_bot
username:         my_bot
realname:         My Lullizio Bot
channels:         ["#mybot_pwns", "#lullizio_ftw"]
modules_dir:      "lib/modules"
excluded_modules: []
module_config:
  module_value:   "some example value for module usage"
  monkey_file:    "monkey_expr.yml"
