server:           irc.elisa.fi
port:             6667
nick:             my_bot
username:         my_bot
realname:         My Lullizio Bot
channels:         ["#mybot_pwns", "#lullizio_ftw"]
modules_dir:      modules
excluded_modules: ["youtube"]
module_config:
  module_value:   "some example value for module usage"
